Add files via upload
cure-dao/draft-whitepaper pull request #165
Opened 2022-02-06 19:10 UTC by agelesspartners

2022-02-06 19:16 UTC, vincenzodomina requested changes
Please add markdown as well

2022-02-07 00:55 UTC, mikepsinn approved these changes

2022-02-07 02:46 UTC, mikepsinn commented
Thanks, @agelesspartners !  😄 We probably want to be more specific in pull request naming to make it easier to search in the future or make sense when going through the git commit history.

2022-02-07 09:15 UTC, vincenzodomina approved these changes

2022-02-07 09:16 UTC, merged

2022-02-07 14:45 UTC, agelesspartners commented
> Thanks, @agelesspartners ! 😄 We probably want to be more specific in pull request naming to make it easier to search in the future or make sense when going through the git commit history.

Agreed! I'll look to be more specific on the naming of the pull requests. Thank you.